### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by NickVanOosterwyck** [stoani89/LaTeX2AI#21] opened 2020-12-07 13:51 UTC
I would love to use your plugin! I added the .exe and .aip file to the plugin folder, but get an error when opening Illustrator. Both MikTex and Ghostscript are installed.
![afbeelding](https://user-images.githubusercontent.com/36815611/101358426-1cd8f900-389b-11eb-8a07-c3283a0551b9.png)

**Comment by NickVanOosterwyck** [comment] 2020-12-07 13:54
Installd software: Illustrator 2021, MikTex 2.9, Ghostscript 9.26

**Comment by stoani89** [comment] 2020-12-07 17:10
The problem is very likely due to the different Illustrator versions. The provided binaries are compiled for Illustrator CS6. I did a quick check, as it turns out, the SDK interface did not change too much since CS6 (see a44e75a). You can try if it works on your system with the attached [debug binaries](https://github.com/stoani89/LaTeX2AI/files/5654115/LaTeX2AI_Illustrator2021_debug.zip).

**Comment by stoani89** [comment] 2020-12-13 23:33
@NickVanOosterwyck did you get it to work with the CS2021 binaries? If so, could you run the test suite ![testing_light](https://user-images.githubusercontent.com/171502/102027380-e40db800-3da3-11eb-955b-bfcc8466f087.png) and send me the output?

**Comment by stoani89** [comment] 2020-12-30 17:39
With the newest release, LaTeX2AI supports Illustrator2021. Therefore, I am closing this issue. If you run into other problems, feel free to open another issue.

**Closed by stoani89** 2020-12-30 17:39 UTC
